# Generated by Django 2.0.5 on 2018-05-15 12:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вечерники')),
                ('date', models.DateField()),
                ('time_start', models.TimeField(default=datetime.time(22, 0))),
                ('time_end', models.TimeField(default=datetime.time(6, 0))),
                ('description', markdownx.models.MarkdownxField(verbose_name='Описание мероприятия')),
                ('repeat', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('on_main', models.BooleanField(default=True)),
                ('poster', models.ImageField(upload_to='')),
                ('poster_alt', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Вечерники',
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Место проведения мероприятия')),
                ('location', models.CharField(default='пр-кт Испытателей 26/2', max_length=255, verbose_name='Адрес')),
                ('price', markdownx.models.MarkdownxField(verbose_name='Цены на вход')),
            ],
            options={
                'verbose_name_plural': 'Вечерники',
            },
        ),
        migrations.AddField(
            model_name='party',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='REST.Places'),
        ),
    ]
