# Generated by Django 2.0.5 on 2018-05-15 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places',
            options={'verbose_name_plural': 'Категории вечеринок'},
        ),
    ]
